name: Docker CI

on:
  push:
    branches:
      - main   # change to master if your repo uses master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check Docker
        run: docker --version

      - name: Build image
        run: docker build -t my-app .
